interface Food {
    id: number;
    foodCategoryId: number;
    name: string;
    water: string;
    calories: string;
    protein: string;
    totalFat: string;
    sfa: string;
    mufa: string;
    pufa: string;
    cholesterol: string;
    carbs: string;
    sugar: string;
    ash: string;
    dietaryFiber: string;
    calcium: string;
    iron: string;
    magnesium: string;
    phosphorus: string;
    potassium: string;
    sodium: string;
    zinc: string;
    copper: string;
    selenium: string;
    edibleFraction: string;
    vitaminC: string;
    thiamine: string;
    riboflavin: string;
    niacin: string;
    vitaminB5: string | null;
    vitaminB6: string;
    folicAcid: string;
    folate: string;
    foodBasedFolate: string;
    vitaminB12: string;
    vitaminA: string;
    retinol: string;
    carotenoids: string;
    vitaminE: string;
    vitaminD: string;
    vitaminK: string;
    priceTierId: number | null;
    imageId: number | null;
    editedById: number | null;
    isEdited: boolean;
    foodCategory: FoodCategory;
    priceTier: number | null;
    editedBy: number | null;
    image: Image;
}