interface Food {
    id: number;
    foodCategoryId: number;
    name: string;
    water: string;
    calories: string;
    protein: string;
    totalFat: string;
    sfa: string;
    mufa: string;
    pufa: string;
    cholesterol: string;
    carbs: string;
    sugar: string;
    ash: string;
    dietaryFiber: string;
    calcium: string;
    iron: string;
    magnesium: string;
    phosphorus: string;
    potassium: string;
    sodium: string;
    zinc: string;
    copper: string;
    selenium: string;
    edibleFraction: string;
    vitaminC: string;
    thiamine: string;
    riboflavin: string;
    niacin: string;
    vitaminB5: string | null;
    vitaminB6: string;
    folicAcid: string;
    folate: string;
    foodBasedFolate: string;
    vitaminB12: string;
    vitaminA: string;
    retinol: string;
    carotenoids: string;
    vitaminE: string;
    vitaminD: string;
    vitaminK: string;
    priceTierId: number | null;
    imageId: number | null;
    hasMeat: boolean | null;
    hasEggs: boolean | null;
    hasMilk: boolean | null;
    hasHoney: boolean | null;
    hasGluten: boolean | null;
    isOvoLactoVegetarian: boolean | null;
    isLactoVegetarian: boolean | null;
    isOvoVegetarian: boolean | null;
    isVegan: boolean | null;
    isGlutenFree: boolean | null;
    canBeADish: boolean | null;
    editedById: number | null;
    isEdited: boolean;
    foodCategory: FoodCategory;
    editedBy: {
        "firstName": string,
        "lastName": string
    } | null;
    priceTier: number | null;
    editedBy: number | null;
    image: Image | null;
}
